#!/usr/bin/env python3
OUT = open("app_native.py", "w", encoding="utf-8")
def w(s): OUT.write(s+"\n")
w("# -*- coding: utf-8 -*-")
w("# ClawMemory Native GUI - PySimpleGUI Windows")
w("import sys, os, json, re, sqlite3, time, uuid")
w("from pathlib import Path")
w("from datetime import datetime, timezone")
w("CLAWMEM = Path(__file__).parent")
w("DBP = CLAWMEM/'data'/'store'/'memory.db'")
w("DBP.parent.mkdir(exist_ok=True)")
w("PM={'PUBLIC':0,'INTERNAL':1,'PRIVATE':2,'STRICT':3}")
w("PR={v:k for k,v in PM.items()}")
w("IMP=['低','中','高','关键']")
w("CI={'all':'📋','general':'📌','learning':'📚','work':'💼','life':'🏠','idea':'💡','fact':'📝','emotion':'❤️'}")
w("CL={'all':'全部','general':'通用','learning':'学习','work':'工作','life':'生活','idea':'创意','fact':'事实','emotion':'情感'}")
w("PI={'PUBLIC':'🟢','INTERNAL':'🟡','PRIVATE':'🔴','STRICT':'🟣'}")
w("def sp(t):")
w(" d=[]")
w(" if re.search(r'密码|口令|账号',t,re.I): d.append('PASSWORD')")
w(" if re.search(r'身份证|护照',t,re.I): d.append('ID_CARD')")
w(" if re.search(r'1[3-9]\\d{9}',t): d.append('PHONE')")
w(" if re.search(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',t): d.append('EMAIL')")
w(" if not d: return False,[],'INTERNAL'")
w(" sv={'PASSWORD':3,'ID_CARD':3,'PHONE':1,'EMAIL':1}")
w(" mx=max(sv.get(t,0) for t in d)")
w(" lv={0:'PUBLIC',1:'PRIVATE',2:'PRIVATE',3:'STRICT'}")
w(" return True,d,lv.get(mx,'INTERNAL')")
w("def sc(t):")
w(" t=t.lower()")
w(" if any(k in t for k in['会议','项目','task','meeting','project']): return 'work'")
w(" if any(k in t for k in['学习','课程','course','study']): return 'learning'")
w(" if any(k in t for k in['想法','创意','idea','think']): return 'idea'")
w(" if any(k in t for k in['密码','账号','password']): return 'fact'")
w(" if any(k in t for k in['感受','心情','feel','happy']): return 'emotion'")
w(" return 'general'")
w("def st(t):")
w(" return list({**dict.fromkeys([m.lower() for m in re.findall(r'[@#](\\w+)',t)]+['url:'+m[:30]for m in re.findall(r'https?://\\S+',t)]))[:8]")
w("def idb():")
w(" c=sqlite3.connect(str(DBP));cu=c.cursor()")
w(" cu.executescript('PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS memories(id TEXT PRIMARY KEY,content TEXT NOT NULL,plaintext_preview TEXT,category TEXT DEFAULT\"general\",tags TEXT DEFAULT\"[]\",privacy INTEGER DEFAULT 1,importance INTEGER DEFAULT 2,source_session TEXT DEFAULT\"gui\",source_agent TEXT DEFAULT\"gui\",created_at REAL,updated_at REAL,accessed_at REAL,access_count INTEGER DEFAULT 0,is_deleted INTEGER DEFAULT 0,metadata_json TEXT DEFAULT\"{}\");CREATE INDEX IF NOT EXISTS idx_cat ON memories(category)WHERE is_deleted=0;CREATE INDEX IF NOT EXISTS idx_priv ON memories(privacy)WHERE is_deleted=0;CREATE INDEX IF NOT EXISTS idx_updated ON memories(updated_at)WHERE is_deleted=0;')")
w(" c.commit();c.close()")
w("def am(cat,tags,priv,imp):")
w(" m=str(uuid.uuid4());n=time.time();c=sqlite3.connect(str(DBP));cu=c.cursor()")
w(" cu.execute('INSERT INTO memories(id,content,plaintext_preview,category,tags,privacy,importance,source_session,source_agent,created_at,updated_at,accessed_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',(m,cat,cat[:200],cat,json.dumps(tags,ensure_ascii=False),PM.get(priv,1),imp,'gui','gui',n,n,n)")
w(" c.commit();c.close();return m")
w("def gm(c='all',p='all',s=''):")
w(" c=sqlite3.connect(str(DBP));cu=c.cursor()")
w(" sql='SELECT id,content,category,tags,privacy,importance,created_at,updated_at,accessed_at,access_count FROM memories WHERE is_deleted=0'")
w(" par=[]")
w(" if c!='all': sql+=' AND category=?';par.append(c)")
w(" if p!='all': sql+=' AND privacy=?';par.append(PM.get(p,1))")
w(" if s: sql+=' AND(content LIKE ? OR tags LIKE ? OR category LIKE?)';ss='%'+s+'%';par.extend([ss,ss,ss])")
w(" sql+=' ORDER BY updated_at DESC LIMIT 200'")
w(" rows=cu.execute(sql,par).fetchall();c.close()")
w(" return[{'id':r[0],'content':r[1],'category':r[2],'tags':json.loads(r[3]),'privacy':PR.get(r[4],'INTERNAL'),'importance':r[5],'created_at':r[6],'updated_at':r[7],'accessed_at':r[8],'access_count':r[9]}for r in rows]")
w("def gmi(m):")
w(" c=sqlite3.connect(str(DBP));cu=c.cursor()")
w(" r=cu.execute('SELECT id,content,category,tags,privacy,importance,created_at,updated_at,accessed_at,access_count FROM memories WHERE id=?AND is_deleted=0',(m,)).fetchone();c.close()")
w(" if not r: return None")
w(" return{'id':r[0],'content':r[1],'category':r[2],'tags':json.loads(r[3]),'privacy':PR.get(r[4],'INTERNAL'),'importance':r[5],'created_at':r[6],'updated_at':r[7],'accessed_at':r[8],'access_count':r[9]}")
w("def dm(m):")
w(" c=sqlite3.connect(str(DBP));cu=c.cursor()")
w(" cu.execute('UPDATE memories SET is_deleted=1,updated_at=?WHERE id=?',(time.time(),m))")
w(" c.commit();c.close()")
w("def um(m,cat,tags,priv,imp):")
w(" n=time.time();c=sqlite3.connect(str(DBP));cu=c.cursor()")
w(" cu.execute('UPDATE memories SET content=?,category=?,tags=?,privacy=?,importance=?,updated_at=?,plaintext_preview=?WHERE id=?',(cat,json.dumps(tags,ensure_ascii=False),PM.get(priv,1),imp,n,cat[:200],m)")
w(" c.commit();a=cu.execute('SELECT COUNT(*)FROM memories WHERE id=?',(m,)).fetchone()[0];c.close();return a>0")
w("def gs():")
w(" c=sqlite3.connect(str(DBP));cu=c.cursor()")
w(" tot=cu.execute('SELECT COUNT(*)FROM memories WHERE is_deleted=0').fetchone()[0]")
w(" bp={k:cu.execute('SELECT COUNT(*)FROM memories WHERE privacy=?AND is_deleted=0',(v,)).fetchone()[0]for k,v in PR.items()}")
w(" cats=dict(cu.execute('SELECT category,COUNT(*)FROM memories WHERE is_deleted=0 GROUP BY category ORDER BY COUNT(*)DESC').fetchall())")
w(" sz=DBP.stat().st_size if DBP.exists()else 0;c.close()")
w(" return{'total':tot,'by_privacy':bp,'top_categories':cats,'db_size':sz}")
w("def sd():")
w(" if DBP.exists()and sqlite3.connect(str(DBP)).execute('SELECT COUNT(*)FROM memories').fetchone()[0]>0:return")
w(" demos=[")
w("  ('今天完成了 ClawMemory v1.0 核心架构设计，包括 AES-256 加密引擎、SQLite 存储引擎和 TF-IDF 向量索引。整体采用分层模块化设计。','learning',['ai','architecture','python'],'INTERNAL',3),")
w("  ('Q2 产品路线图：6月完成核心功能，9月支持多 Agent 协同记忆，12月跨设备同步。','work',['roadmap','planning'],'INTERNAL',3),")
w("  ('AI Agent 终身记忆是近两年最有价值的创业方向。核心壁垒：数据飞轮效应、隐私计算基础设施。','idea',['startup','ai','memory'],'PUBLIC',2),")
w("  ('ClawMemory 支持四级隐私分级：PUBLIC / INTERNAL / PRIVATE / STRICT。STRICT 级别物理隔离存储。','learning',['privacy','security','architecture'],'INTERNAL',2),")
w(" ]")
w(" for cat,tags,priv,imp in demos: am(cat,tags,priv,imp)")
OUT.close()
print("Part 1 written! Length:", open("app_native.py","r",encoding="utf-8").read().__len__(), "chars")
