#!/usr/bin/env python3
# gen1.py - Generate ClawMemory app_native.py (Part 1)
OUT = open("app_native.py", "w", encoding="utf-8")

def w(s):
    OUT.write(s + "\n")

w("# -*- coding: utf-8 -*-")
w("# ClawMemory Native GUI - PySimpleGUI Windows Application")
w("import sys, os, json, re, sqlite3, time, uuid")
w("from pathlib import Path")
w("from datetime import datetime, timezone")
w("")
w("CLAWMEMORY_DIR = Path(__file__).parent")
w("DB_PATH = CLAWMEMORY_DIR / 'data' / 'store' / 'memory.db'")
w("DB_PATH.parent.mkdir(exist_ok=True)")
w("")
w("PM = {'PUBLIC': 0, 'INTERNAL': 1, 'PRIVATE': 2, 'STRICT': 3}")
w("PR = {v: k for k, v in PM.items()}")
w("IMP = ['低', '中', '高', '关键']")
w("CAT_IC = {'all':'📋','general':'📌','learning':'📚','work':'💼','life':'🏠','idea':'💡','fact':'📝','emotion':'❤️'}")
w("CAT_LB = {'all':'全部','general':'通用','learning':'学习','work':'工作','life':'生活','idea':'创意','fact':'事实','emotion':'情感'}")
w("PRIV_IC = {'PUBLIC':'🟢','INTERNAL':'🟡','PRIVATE':'🔴','STRICT':'🟣'}")
w("")
w("def scan_privacy(text):")
w("    det = []")
w("    if re.search(r'密码|口令|账号', text, re.I): det.append('PASSWORD')")
w("    if re.search(r'身份证|护照', text, re.I): det.append('ID_CARD')")
w("    if re.search(r'1[3-9]\\d{9}', text): det.append('PHONE')")
w("    if re.search(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}', text): det.append('EMAIL')")
w("    if not det: return False, [], 'INTERNAL'")
w("    sev = {'PASSWORD': 3, 'ID_CARD': 3, 'PHONE': 1, 'EMAIL': 1}")
w("    mx = max(sev.get(t, 0) for t in det)")
w("    lvls = {0: 'PUBLIC', 1: 'PRIVATE', 2: 'PRIVATE', 3: 'STRICT'}")
w("    return True, det, lvls.get(mx, 'INTERNAL')")
w("")
w("def suggest_category(text):")
w("    t = text.lower()")
w("    if any(k in t for k in ['会议','项目','task','meeting','project']): return 'work'")
w("    if any(k in t for k in ['学习','课程','书','course','study']): return 'learning'")
w("    if any(k in t for k in ['想法','创意','idea','think']): return 'idea'")
w("    if any(k in t for k in ['密码','账号','地址','password']): return 'fact'")
w("    if any(k in t for k in ['感受','心情','feel','happy']): return 'emotion'")
w("    return 'general'")
w("")
w("def suggest_tags(text):")
w("    tags = [m.lower() for m in re.findall(r'[@#](\\w+)', text)]")
w("    for m in re.findall(r'https?://\\S+', text): tags.append('url:' + m[:30])")
w("    return list(dict.fromkeys(tags))[:8]")
w("")
w("def init_db():")
w("    conn = sqlite3.connect(str(DB_PATH)); c = conn.cursor()")
w("    c.executescript(\"PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS memories (id TEXT PRIMARY KEY,content TEXT NOT NULL,plaintext_preview TEXT,category TEXT DEFAULT 'general',tags TEXT DEFAULT '[]',privacy INTEGER DEFAULT 1,importance INTEGER DEFAULT 2,source_session TEXT DEFAULT 'gui',source_agent TEXT DEFAULT 'gui',created_at REAL,updated_at REAL,accessed_at REAL,access_count INTEGER DEFAULT 0,is_deleted INTEGER DEFAULT 0,metadata_json TEXT DEFAULT '{}');CREATE INDEX IF NOT EXISTS idx_cat ON memories(category) WHERE is_deleted=0;CREATE INDEX IF NOT EXISTS idx_priv ON memories(privacy) WHERE is_deleted=0;CREATE INDEX IF NOT EXISTS idx_updated ON memories(updated_at) WHERE is_deleted=0;\")")
w("    conn.commit(); conn.close()")
w("")
w("def add_memory(content, category, tags, privacy, importance):")
w("    mid = str(uuid.uuid4()); now = time.time()")
w("    conn = sqlite3.connect(str(DB_PATH)); c = conn.cursor()")
w("    c.execute('INSERT INTO memories (id,content,plaintext_preview,category,tags,privacy,importance,source_session,source_agent,created_at,updated_at,accessed_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',")
w("        mid, content, content[:200], category, json.dumps(tags, ensure_ascii=False), PM.get(privacy,1), importance, 'gui','gui', now,now,now)")
w("    conn.commit(); conn.close(); return mid")
w("")
w("def get_memories(category='all', privacy='all', search=''):")
w("    conn = sqlite3.connect(str(DB_PATH)); c = conn.cursor()")
w("    sql = 'SELECT id,content,category,tags,privacy,importance,created_at,updated_at,accessed_at,access_count FROM memories WHERE is_deleted=0'")
w("    params = []")
w("    if category != 'all': sql += ' AND category=?'; params.append(category)")
w("    if privacy != 'all': sql += ' AND privacy=?'; params.append(PM.get(privacy,1))")
w("    if search: sql += ' AND (content LIKE ? OR tags LIKE ? OR category LIKE ?)'; s = '%'+search+'%'; params.extend([s,s,s])")
w("    sql += ' ORDER BY updated_at DESC LIMIT 200'")
w("    rows = c.execute(sql, params).fetchall(); conn.close()")
w("    return [{'id':r[0],'content':r[1],'category':r[2],'tags':json.loads(r[3]),")
w("             'privacy':PR.get(r[4],'INTERNAL'),'importance':r[5],")
w("             'created_at':r[6],'updated_at':r[7],'accessed_at':r[8],'access_count':r[9]} for r in rows]")
w("")
w("def get_memory_by_id(mid):")
w("    conn = sqlite3.connect(str(DB_PATH)); c = conn.cursor()")
w("    row = c.execute('SELECT id,content,category,tags,privacy,importance,created_at,updated_at,accessed_at,access_count FROM memories WHERE id=? AND is_deleted=0',(mid,)).fetchone()")
w("    conn.close()")
w("    if not row: return None")
w("    return {'id':row[0],'content':row[1],'category':row[2],'tags':json.loads(row[3]),")
w("             'privacy':PR.get(row[4],'INTERNAL'),'importance':row[5],")
w("             'created_at':row[6],'updated_at':row[7],'accessed_at':row[8],'access_count':row[9]}")
w("")
w("def delete_memory(mid):")
w("    conn = sqlite3.connect(str(DB_PATH)); c = conn.cursor()")
w("    c.execute('UPDATE memories SET is_deleted=1,updated_at=? WHERE id=?',(time.time(),mid))")
w("    conn.commit(); conn.close()")
w("")
w("def update_memory(mid, content, category, tags, privacy, importance):")
w("    now = time.time(); conn = sqlite3.connect(str(DB_PATH)); c = conn.cursor()")
w("    c.execute('UPDATE memories SET content=?,category=?,tags=?,privacy=?,importance=?,updated_at=?,plaintext_preview=? WHERE id=?'")
w("        ,(content, category, json.dumps(tags, ensure_ascii=False), PM.get(privacy,1), importance, now, content[:200], mid)")
w("    conn.commit(); aff = c.execute('SELECT COUNT(*) FROM memories WHERE id=?',(mid,)).fetchone()[0]; conn.close()")
w("    return aff > 0")
w("")
w("def get_stats():")
w("    conn = sqlite3.connect(str(DB_PATH)); c = conn.cursor()")
w("    total = c.execute('SELECT COUNT(*) FROM memories WHERE is_deleted=0').fetchone()[0]")
w("    by_priv = {k: c.execute('SELECT COUNT(*) FROM memories WHERE privacy=? AND is_deleted=0',(v,)).fetchone()[0] for k,v in PR.items()}")
w("    cats = dict(c.execute('SELECT category,COUNT(*) FROM memories WHERE is_deleted=0 GROUP BY category ORDER BY COUNT(*) DESC').fetchall())")
w("    db_size = DB_PATH.stat().st_size if DB_PATH.exists() else 0; conn.close()")
w("    return {'total':total,'by_privacy':by_priv,'top_categories':cats,'db_size':db_size}")
w("")
w("def seed_demo():")
w("    if DB_PATH.exists() and sqlite3.connect(str(DB_PATH)).execute('SELECT COUNT(*) FROM memories').fetchone()[0] > 0: return")
w("    demos = [")
w("        ('今天完成了 ClawMemory v1.0 核心架构设计，包括 AES-256 加密引擎、SQLite 存储引擎和 TF-IDF 向量索引。整体采用分层模块化设计。', 'learning', ['ai','architecture','python'], 'INTERNAL', 3),")
w("        ('Q2 产品路线图：6月完成核心功能，9月支持多 Agent 协同记忆，12月跨设备同步。', 'work', ['roadmap','planning'], 'INTERNAL', 3),")
w("        ('AI Agent 终身记忆是近两年最有价值的创业方向。核心壁垒：数据飞轮效应、隐私计算基础设施、Agent 原生架构。', 'idea', ['startup','ai','memory'], 'PUBLIC', 2),")
w("        ('ClawMemory 支持四级隐私分级：PUBLIC / INTERNAL / PRIVATE / STRICT。STRICT 级别物理隔离存储，ACL 访问授权。', 'learning', ['privacy','security','architecture'], 'INTERNAL', 2),")
w("    ]")
w("    for content,cat,tags,priv,imp in demos: add_memory(content,cat,tags,priv,imp)")
w("")
w("import PySimpleGUI as sg")
w("sg.theme('DarkGrey13')")
w("sg.set_options(font=('Segoe UI',10), text_color='#e2e8f0', background_color='#0d1422',")
w("    input_background_color='#0a1020', button_color=('#0d1422','#00d4ff'),")
w("    element_background_color='#0d1422', border_width=1)")
w("")
w("def time_ago(ts):")
w("    d = time.time()-ts; m = int(d/60)")
w("    if m < 1: return '刚刚'")
w("    if m < 60: return str(m)+'分钟前'")
w("    h = int(m/60)")
w("    if h < 24: return str(h)+'小时前'")
w("    dd = int(h/24)")
w("    if dd < 30: return str(dd)+'天前'")
w("    return datetime.fromtimestamp(ts).strftime('%Y-%m-%d')")
w("")
w("def cat_color(c):")
w("    return {'learning':'#f59e0b','work':'#00d4ff','life':'#f472b6','idea':'#a855f7','fact':'#10b981','emotion':'#ef4444','general':'#64748b'}.get(c,'#00d4ff')")
w("")
w("def make_card(mem):")
w("    acc = cat_color(mem['category'])")
w("    priv_icon = PRIV_IC.get(mem['privacy'],'🟡')")
w("    content_short = mem['content'][:100].replace('\\n',' ').strip()")
w("    tags_str = '  '.join('#'+t for t in mem['tags'][:4])")
w("    time_str = time_ago(mem['updated_at'])")
w("    imp_lbl = IMP[mem['importance']-1]")
w("    cat_icon = CAT_IC.get(mem['category'],'📌')")
w("    cat_lbl = CAT_LB.get(mem['category'], mem['category'])")
w("    mid = mem['id']")
w("    col_layout = [")
w("        [sg.Text(cat_icon+' '+cat_lbl, font=('Segoe UI',9,'bold'), text_color=acc, pad=(8,(8,0))),")
w("         sg.Text(priv_icon+' '+mem['privacy'], font=('Segoe UI',8), text_color='#64748b', pad=(0,(8,0)), expand_x=True, justification='right'),")
w("         sg.Button('✕', key='del:'+mid, button_color=('transparent','transparent'), text_color='#ef4444', font=('Segoe UI',9), Size=(2,1), pad=(4,(4,0)), tooltip='删除记忆')], ")
w("        [sg.Text(content_short+('...' if len(mem['content'])>100 else ''), text_color='#94a3b8', font=('Segoe UI',9), pad=(8,(2,0)), expand_x=True, tooltip=mem['content'][:300])],")
w("        [sg.Text(tags_str+'  · '+time_str+'  · '+imp_lbl+'重要', font=('Segoe UI',8), text_color='#475569', pad=(8,(4,8)))], ")
w("    ]")
w("    return sg.Column(col_layout, background_color='#111a2e', pad=(0,4), expand_x=True, key='card:'+mid, metadata={'mem_id':mid})")
w("")
w("def build_cards(mems):")
w("    if not mems: return [[sg.Text('🔍 暂无记忆', text_color='#334155', font=('Segoe UI',11), justification='center', pad=(20,40))]]")
w("    return [[make_card(m)] for m in mems]")
w("")
w("def refresh(window, cat='all', search=''):")
w("    mems = get_memories(category=cat, search=search)")
w("    s = get_stats()")
w("    window['stat_text'].update('📊 '+str(s['total'])+' 条记忆')")
w("    window['memory_area'].update([[sg.Column(build_cards(mems), expand_x=True, background_color='#0d1422', element_justification='left', vertical_scroll_only=True)]])")
w("    cat_lbl = CAT_LB.get(cat, cat)")
w("    window['status_text'].update('显示 '+str(len(mems))+' 条 '+cat_lbl+' 记忆')")
w("")
w("def make_stats_win():")
w("    s = get_stats(); sz = s['db_size']")
w("    sz_str = f'{sz/1024:.1f} KB' if sz < 1048576 else f'{sz/1048576:.1f} MB'")
w("    pcols = {'PUBLIC':'#10b981','INTERNAL':'#f59e0b','PRIVATE':'#ef4444','STRICT':'#a855f7'}")
w("    prow = [sg.Text(PRIV_IC.get(k,'🟢')+' '+k+': '+str(v)+' 条', text_color=pcols.get(k,'#94a3b8'), font=('Segoe UI',10,'bold')) for k,v in s.get('by_privacy',{}).items()]")
w("    crow = [sg.Text('  '+CAT_IC.get(k,'📌')+' '+CAT_LB.get(k,k)+': '+str(v)+' 条', text_color='#94a3b8') for k,v in list(s.get('top_categories',{}).items())[:10]]")
w("    return sg.Window('📊统计报告 - ClawMemory',[")
w("        [sg.Text('📊 ClawMemory 统计报告', font=('Segoe UI',14,'bold'), text_color='#00d4ff')],")
w("        [sg.HorizontalSeparator(color='#1e3a5f')],")
w("        [sg.Text('总记忆数:  '+str(s['total']), font=('Segoe UI',11,'bold'), text_color='#e2e8f0', pad=(0,6))],")
w("        [sg.Text('数据库大小:  '+sz_str, font=('Segoe UI',10), text_color='#64748b', pad=(0,6))],")
w("        [sg.Text('─ 隐私分级 ─', font=('Segoe UI',9,'bold'), text_color='#334155', pad=(0,4))],*prow,")
w("        [sg.Text('─ 分类 ─', font=('Segoe UI',9,'bold'), text_color='#334155', pad=(0,4))],*crow,")
w("        [sg.Button('关闭', button_color=('#1e293b','#475569'), pad=(0,(16,0)))], ")
w("    ], modal=True, finalize=True, background_color='#0d1422', size=(380,420))")
w("")
OUT.close()
print("Part 1 written!")
